@startuml
title Клиентская часть
Пользователь -> Браузер: Открытие страницы
Браузер -> Сервер: GET запрос главной страницы
Сервер -> Браузер: index.html
Браузер -> Пользователь: Отрисовка интерфейса
Пользователь -> Браузер: Выбор файла для просмотра
Браузер -> Сервер: Загрузка файла
Сервер -> Браузер: ID файла
Пользователь -> Браузер: Установка\nпараметров рендеринга
Браузер -> Браузер: Считывание параметров рендера
Браузер -> Браузер: Генерирование адреса изображения\nотрисованной модели
Браузер -> Сервер: Запрос изображения /render.php?...
Сервер -> Браузер: Изображение модели в формате .png
Браузер -> Пользователь: Вывод изображения
@enduml